[package]
name = "aptos-landing-contract"
version = "1.0.0"
authors = []

[addresses]
aptos_landing_contract = "4eb9d24d059db22f0f2a858f128f2e747f5ff7c441c2b95c87559aae1c29c4f7"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
